name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build crust
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests with crust
        run: |
          # Set environment variables for debugging and graceful mode
          export CRUST_DEBUG=1
          export CRUST_GRACEFUL_MODE=1
          # Run the all-in-one test harness. Adjust path as necessary.
          LD_PRELOAD=$(pwd)/libcrust.so ./test_program
